import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const modalPath = path.resolve(__dirname, "../features/media/components/MediaViewerModal.jsx");
const appCssPath = path.resolve(__dirname, "../App.css");
const modalSource = readFileSync(modalPath, "utf8");
const appCss = readFileSync(appCssPath, "utf8");

test("media viewer shows related media in thumbnail strip instead of metadata table", () => {
  assert.match(modalSource, /relatedMediaItems/);
  assert.match(modalSource, /const visibleRelatedMediaItems = Array\.isArray\(relatedMediaItems\) && relatedMediaItems\.length > 0/);
  assert.match(modalSource, /relatedMediaStripRef/);
  assert.match(modalSource, /useLayoutEffect/);
  assert.match(modalSource, /getNextMediaFitMode/);
  assert.match(modalSource, /mediaFitMode/);
  assert.match(modalSource, /mediaAssetFrameRef/);
  assert.match(modalSource, /mediaAssetOverflow/);
  assert.match(modalSource, /imageSourceAttempt/);
  assert.match(modalSource, /directViewMediaUrl/);
  assert.match(modalSource, /syncMediaAssetOverflow/);
  assert.match(modalSource, /centerMediaAssetFrame/);
  assert.match(modalSource, /setImageSourceAttempt\("primary"\)/);
  assert.match(modalSource, /\/api\/media\/view\?path=\$\{encodeURIComponent\(file\.relativePath\)\}/);
  assert.match(modalSource, /frame\.scrollLeft = maxScrollLeft \/ 2/);
  assert.match(modalSource, /frame\.scrollTop = maxScrollTop \/ 2/);
  assert.match(modalSource, /className="media-fit-btn"/);
  assert.match(modalSource, /<AppIcon name=\{mediaFitMode\} alt="" aria-hidden="true" \/>/);
  assert.match(modalSource, /frame\.scrollWidth > frame\.clientWidth/);
  assert.match(modalSource, /frame\.scrollHeight > frame\.clientHeight/);
  assert.match(modalSource, /onError=\{\(\) => \{/);
  assert.match(modalSource, /imageSourceAttempt === "primary"/);
  assert.match(modalSource, /setImageSourceAttempt\("original"\)/);
  assert.match(modalSource, /setImageSourceAttempt\("preview"\)/);
  assert.match(modalSource, /media-modal-asset-frame media-modal-asset-frame-\$\{mediaFitMode\}\$\{mediaAssetOverflow\.x \? " is-overflow-x" : ""\}\$\{mediaAssetOverflow\.y \? " is-overflow-y" : ""\}/);
  assert.match(modalSource, /syncMediaAssetOverflow\(\);\s*centerMediaAssetFrame\(\);/);
  assert.match(modalSource, /media-modal-fit-\$\{mediaFitMode\}/);
  assert.match(modalSource, /innerFrameId/);
  assert.match(modalSource, /getBoundingClientRect\(\)/);
  assert.match(modalSource, /scrollTo\(\{/);
  assert.match(modalSource, /addEventListener\("resize", centerActiveRelatedMedia\)/);
  assert.match(modalSource, /className="media-related-strip"/);
  assert.match(modalSource, /key=\{relatedId \|\| item\.relativePath \|\| "unknown"\}/);
  assert.match(modalSource, /visibleRelatedMediaItems\.map/);
  assert.doesNotMatch(modalSource, /media-related-card-label/);
  assert.doesNotMatch(modalSource, /<th scope="row">Parent<\/th>/);
  assert.doesNotMatch(modalSource, /<th scope="row">Child<\/th>/);
});

test("media viewer defines related media strip styles", () => {
  const mobileMediaViewerStyles = appCss.match(/@media \(max-width: 760px\) \{[\s\S]*?\.media-modal-content \.media-modal-fit-width[\s\S]*?\n\}/);

  assert.ok(mobileMediaViewerStyles, "Expected mobile media viewer styles to exist");
  assert.match(appCss, /\.media-fit-btn/);
  assert.match(appCss, /\.media-fit-btn \.app-icon/);
  assert.match(appCss, /\.media-modal-asset-frame/);
  assert.match(appCss, /\.media-modal-asset-frame-height,/);
  assert.match(appCss, /overflow:\s*auto/);
  assert.match(appCss, /\.media-modal-asset-frame\.is-overflow-x/);
  assert.match(appCss, /\.media-modal-asset-frame\.is-overflow-y/);
  assert.match(appCss, /justify-content:\s*flex-start/);
  assert.match(appCss, /align-items:\s*flex-start/);
  assert.match(appCss, /\.media-modal-asset/);
  assert.match(appCss, /\.media-modal-fit-height/);
  assert.match(appCss, /\.media-modal-fit-width/);
  assert.match(appCss, /\.media-related-strip/);
  assert.match(appCss, /\.media-related-card-thumb-wrap/);
  assert.match(appCss, /background:\s*transparent/);
  assert.match(appCss, /--media-related-card-size:\s*clamp\(3\.4rem, 9dvh, 6rem\)/);
  assert.match(appCss, /--media-related-thumb-size:\s*calc\(var\(--media-related-card-size\) - \(var\(--media-related-card-padding\) \* 2\)\)/);
  assert.match(appCss, /padding:\s*0\.2rem calc\(50% - \(var\(--media-related-card-size\) \/ 2\) - 0\.4rem\)/);
  assert.match(appCss, /scrollbar-width:\s*none/);
  assert.match(appCss, /\.media-related-card\.is-current/);
  assert.match(appCss, /border-color:\s*transparent/);
  assert.match(appCss, /box-shadow:\s*none/);
  assert.match(appCss, /justify-content:\s*flex-start/);
  assert.match(appCss, /padding-top:\s*calc\(0\.75rem \+ env\(safe-area-inset-top, 0px\)\)/);
  assert.doesNotMatch(mobileMediaViewerStyles[0], /\.media-modal-meta[\s\S]*?overflow-y:\s*auto/);
  assert.match(mobileMediaViewerStyles[0], /justify-content:\s*flex-start/);
  assert.match(mobileMediaViewerStyles[0], /--media-related-card-size:\s*clamp\(3rem, 7dvh, 4\.5rem\)/);
  assert.match(mobileMediaViewerStyles[0], /--media-related-card-padding:\s*0\.25rem/);
  assert.match(mobileMediaViewerStyles[0], /grid-template-rows:\s*auto auto auto/);
  assert.match(mobileMediaViewerStyles[0], /overflow-y:\s*auto/);
  assert.match(mobileMediaViewerStyles[0], /overflow-y:\s*visible/);
  assert.match(mobileMediaViewerStyles[0], /min-height:\s*clamp\(220px, 60vh, 32rem\)/);
  assert.match(mobileMediaViewerStyles[0], /\.media-modal-content \.media-modal-fit-height/);
  assert.match(mobileMediaViewerStyles[0], /\.media-modal-content \.media-modal-fit-width/);
  assert.match(mobileMediaViewerStyles[0], /max-height:\s*none/);
  assert.match(mobileMediaViewerStyles[0], /width:\s*var\(--media-related-thumb-size\)/);
  assert.match(mobileMediaViewerStyles[0], /height:\s*var\(--media-related-thumb-size\)/);
});
