import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const appShellSource = readFileSync(path.resolve(__dirname, "../app/AppShell.jsx"), "utf8");
const iconPathsSource = readFileSync(path.resolve(__dirname, "../features/shared/utils/iconPaths.js"), "utf8");
const settingsContainerSource = readFileSync(path.resolve(__dirname, "../features/settings/SettingsContainer.jsx"), "utf8");
const settingsPageSource = readFileSync(path.resolve(__dirname, "../features/settings/SettingsPage.jsx"), "utf8");
const appSettingsSource = readFileSync(path.resolve(__dirname, "../features/settings/utils/appSettings.js"), "utf8");
const recommendationSettingsSource = readFileSync(path.resolve(__dirname, "../features/settings/utils/recommendationSettings.js"), "utf8");
const appCss = readFileSync(path.resolve(__dirname, "../App.css"), "utf8");

test("AppShell exposes settings in the slide menu and renders settings container", () => {
  assert.match(appShellSource, /import SettingsContainer from "\.\.\/features\/settings\/SettingsContainer"/);
  assert.match(appShellSource, /const openSettingsPage = \(\) => \{/);
  assert.match(appShellSource, /<AppIcon name="settings" alt="" aria-hidden="true" \/>/);
  assert.match(appShellSource, /<span>Settings<\/span>/);
  assert.match(appShellSource, /activePage === "settings" \? \(\s*<SettingsContainer[\s\S]*appSettings=\{appSettings\}[\s\S]*onAppSettingsChange=\{/);
});

test("settings page uses the dedicated icon and page layout", () => {
  assert.match(iconPathsSource, /settings:\s*"\/icons\/settings\.png"/);
  assert.match(settingsContainerSource, /appSettings=\{appSettings\}/);
  assert.match(settingsContainerSource, /onAppSettingsChange=\{onAppSettingsChange\}/);
  assert.match(settingsPageSource, /className="settings-page"/);
  assert.doesNotMatch(settingsPageSource, /settings-page-title/);
  assert.doesNotMatch(settingsPageSource, /settings-intro/);
  assert.match(settingsPageSource, /className="settings-section"/);
  assert.match(settingsPageSource, /className="settings-section-header"/);
  assert.match(settingsPageSource, /className="settings-option"/);
  assert.match(settingsPageSource, /Group related media by default/);
  assert.match(settingsPageSource, /Collapse linked parent\/child media into grouped gallery tiles\./);
  assert.match(settingsPageSource, /Default media fit mode/);
  assert.match(settingsPageSource, /Remember last opened page/);
  assert.match(settingsPageSource, /Remember search history/);
  assert.match(settingsPageSource, /Search suggestions limit/);
  assert.match(settingsPageSource, /Default quick tagging tags/);
  assert.match(settingsPageSource, /Enable group upload mode by default/);
  assert.match(settingsPageSource, /Media grid page size/);
  assert.match(settingsPageSource, /Duplicates page size/);
  assert.match(settingsPageSource, /Show related media strip/);
  assert.match(settingsPageSource, /Confirm destructive actions/);
  assert.match(settingsPageSource, /Load recommendations automatically in viewer/);
  assert.match(settingsPageSource, /Images to display/);
  assert.match(settingsPageSource, /Minimum similarity, %/);
  assert.match(appSettingsSource, /groupRelatedMediaByDefault:\s*false/);
  assert.match(appSettingsSource, /defaultMediaFitMode:\s*"resize"/);
  assert.match(appSettingsSource, /rememberLastOpenedPage:\s*true/);
  assert.match(appSettingsSource, /rememberSearchHistory:\s*true/);
  assert.match(appSettingsSource, /searchSuggestionsLimit:\s*DEFAULT_SEARCH_SUGGESTIONS_LIMIT/);
  assert.match(appSettingsSource, /defaultQuickTaggingTags:\s*""/);
  assert.match(appSettingsSource, /defaultGroupUploadMode:\s*false/);
  assert.match(appSettingsSource, /mediaGridPageSize:\s*36/);
  assert.match(appSettingsSource, /duplicatesPageSize:\s*12/);
  assert.match(appSettingsSource, /showRelatedMediaStrip:\s*true/);
  assert.match(appSettingsSource, /confirmDestructiveActions:\s*true/);
  assert.match(recommendationSettingsSource, /enabled:\s*true/);
  assert.match(recommendationSettingsSource, /visibleCount:\s*12/);
  assert.match(recommendationSettingsSource, /minSimilarityPercent:\s*60/);
  assert.match(appCss, /\.settings-page/);
  assert.doesNotMatch(appCss, /\.settings-intro/);
  assert.match(appCss, /\.settings-section/);
  assert.match(appCss, /\.settings-section-header/);
  assert.match(appCss, /\.settings-grid/);
  assert.match(appCss, /\.settings-option/);
  assert.match(appCss, /\.settings-option-copy/);
  assert.match(appCss, /\.settings-option input\[type="text"\]/);
  assert.match(appCss, /\.settings-option-toggle/);
  assert.doesNotMatch(appCss, /\.settings-field input/);
  assert.doesNotMatch(appCss, /\.settings-checkbox/);
});
