export const MODAL_KEYS = Object.freeze({
  MEDIA_EDITOR: "MEDIA_EDITOR",
  TAG_DELETE_CONFIRM: "TAG_DELETE_CONFIRM",
  COLLECTION_DELETE_CONFIRM: "COLLECTION_DELETE_CONFIRM",
  UPLOAD_DIALOG: "UPLOAD_DIALOG",
  RELATION_PICKER: "RELATION_PICKER"
});
